# Common logic
defaults: &defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Replace Auth0 test credentials
          command: |
            mv $AUTH0_CFG.example $AUTH0_CFG
            sed -i 's/{CLIENT_ID}/'$AUTH0_TEST_CLIENT_ID'/g' $AUTH0_CFG
            sed -i 's/{DOMAIN}/'$AUTH0_TEST_DOMAIN'/g' $AUTH0_CFG
            sed -i 's/{CLIENT_SECRET}/'$AUTH0_TEST_CLIENT_SECRET'/g' $AUTH0_CFG
      - run:
          name: Build pull request
          command: |
            docker build -t $CIRCLE_JOB ./$SAMPLE_PATH
            docker run -d -p 3000:3000 --name $CIRCLE_SHA1 --env-file ./$AUTH0_CFG $CIRCLE_JOB
          background: true
      - run:
          name: Wait for app to be available
          command: |
            sleep 20
            docker run --network host --rm appropriate/curl --retry 8 --retry-connrefused -v localhost:3000
      - run:
          name: Run tests
          command: |
            docker create --network host --name tester codeceptjs/codeceptjs codeceptjs run-multiple --all --steps
            docker cp $(pwd)/lock_login_test.js tester:/tests/lock_login_test.js
            docker cp $(pwd)/codecept.conf.js tester:/tests/codecept.conf.js
            docker start -i tester
          working_directory: scripts
      - run:
          name: Copy app container logs
          command: |
            mkdir -p /tmp/out
            docker logs $CIRCLE_SHA1 > /tmp/out/app_logs.log
            docker cp tester:/tests/out /tmp/
          when: on_fail
      - store_artifacts:
          path: /tmp/out

# Jobs and Workflows
version: 2.1
parameters:
  machine_image:
    type: string
    default: ubuntu-2004:202201-02
jobs:
  checkout:
    machine:
      image: << pipeline.parameters.machine_image >>
    steps:
      - checkout
      - run: git clone https://github.com/auth0-samples/spa-quickstarts-tests scripts
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - scripts
  login:
    machine:
      image: << pipeline.parameters.machine_image >>
    environment:
      - AUTH0_CFG: 01-Login/.env
      - SAMPLE_PATH: 01-Login
    <<: *defaults

workflows:
  version: 2
  quickstarts_login:
    jobs:
      - checkout:
          context: Quickstart Web App Test
      - login:
          context: Quickstart Web App Test
          requires:
            - checkout
